In [1]:
import numpy as np 
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

In [3]:
df=pd.read_csv('loan_data.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  str
 2   person_education                45000 non-null  str
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  str
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  str
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  str
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), str(5)
memory usage: 4.8 MB

In [5]:
df.describe()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,8.031905e+04,5.410333,9583.157556,11.006606,0.139725,5.867489,632.608756,0.222222
std,6.045108,8.042250e+04,6.063532,6314.886691,2.978808,0.087212,3.879702,50.435865,0.415744
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.720400e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704800e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.578925e+04,8.000000,12237.250000,12.990000,0.190000,8.000000,670.000000,0.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000

In [6]:
df=df[df['person_age']<100]

In [7]:
df.describe()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,44993.000000,4.499300e+04,44993.000000,44993.000000,44993.000000,44993.000000,44993.000000,44993.000000,44993.000000
mean,27.748428,7.990845e+04,5.394528,9583.176761,11.006448,0.139736,5.866557,632.585713,0.222257
std,5.909737,6.332213e+04,5.927159,6314.802655,2.978985,0.087207,3.877167,50.402411,0.415767
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.719500e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704600e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.577800e+04,8.000000,12237.000000,12.990000,0.190000,8.000000,670.000000,0.000000
max,94.000000,2.448661e+06,76.000000,35000.000000,20.000000,0.660000,30.000000,784.000000,1.000000

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 44993 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      44993 non-null  float64
 1   person_gender                   44993 non-null  str
 2   person_education                44993 non-null  str
 3   person_income                   44993 non-null  float64
 4   person_emp_exp                  44993 non-null  int64
 5   person_home_ownership           44993 non-null  str
 6   loan_amnt                       44993 non-null  float64
 7   loan_intent                     44993 non-null  str
 8   loan_int_rate                   44993 non-null  float64
 9   loan_percent_income             44993 non-null  float64
 10  cb_person_cred_hist_length      44993 non-null  float64
 11  credit_score                    44993 non-null  int64
 12  previous_loan_defaults_on_file  44993 non-null  str
 13  loan_status                     44993 non-null  int64
dtypes: float64(6), int64(3), str(5)
memory usage: 5.1 MB

In [9]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [10]:
df['person_gender']=df['person_gender'].map({'male':1,'female':0})

In [11]:
cols=['person_education','person_home_ownership','loan_intent','previous_loan_defaults_on_file']

In [12]:
for i in cols: 
    print(df[i].value_counts())

person_education
Bachelor       13396
Associate      12026
High School    11970
Master          6980
Doctorate        621
Name: count, dtype: int64
person_home_ownership
RENT        23440
MORTGAGE    18485
OWN          2951
OTHER         117
Name: count, dtype: int64
loan_intent
EDUCATION            9151
MEDICAL              8548
VENTURE              7815
PERSONAL             7551
DEBTCONSOLIDATION    7145
HOMEIMPROVEMENT      4783
Name: count, dtype: int64
previous_loan_defaults_on_file
Yes    22856
No     22137
Name: count, dtype: int64

In [13]:
df['previous_loan_defaults_on_file']=df['previous_loan_defaults_on_file'].map({'Yes':1,'No':0})

In [15]:
df_encoded=pd.get_dummies(df)

In [16]:
df_encoded=df_encoded.astype(int)

In [17]:
cols=['person_age', 'person_income','person_emp_exp', 'loan_amnt','loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score']

In [18]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [19]:
scalar=StandardScaler()
df_encoded[cols]=scalar.fit_transform(df_encoded[cols])

In [22]:
df_encoded.info()

<class 'pandas.DataFrame'>
Index: 44993 entries, 0 to 44999
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      44993 non-null  float64
 1   person_gender                   44993 non-null  int64
 2   person_income                   44993 non-null  float64
 3   person_emp_exp                  44993 non-null  float64
 4   loan_amnt                       44993 non-null  float64
 5   loan_int_rate                   44993 non-null  float64
 6   loan_percent_income             44993 non-null  float64
 7   cb_person_cred_hist_length      44993 non-null  float64
 8   credit_score                    44993 non-null  float64
 9   previous_loan_defaults_on_file  44993 non-null  int64
 10  loan_status                     44993 non-null  int64
 11  person_education_Associate      44993 non-null  int64
 12  person_education_Bachelor       44993 non-null  int64
 13  person_education_Doctorate      44993 non-null  int64
 14  person_education_High School    44993 non-null  int64
 15  person_education_Master         44993 non-null  int64
 16  person_home_ownership_MORTGAGE  44993 non-null  int64
 17  person_home_ownership_OTHER     44993 non-null  int64
 18  person_home_ownership_OWN       44993 non-null  int64
 19  person_home_ownership_RENT      44993 non-null  int64
 20  loan_intent_DEBTCONSOLIDATION   44993 non-null  int64
 21  loan_intent_EDUCATION           44993 non-null  int64
 22  loan_intent_HOMEIMPROVEMENT     44993 non-null  int64
 23  loan_intent_MEDICAL             44993 non-null  int64
 24  loan_intent_PERSONAL            44993 non-null  int64
 25  loan_intent_VENTURE             44993 non-null  int64
dtypes: float64(8), int64(18)
memory usage: 9.3 MB

In [21]:
Percep=Perceptron(max_iter=1000,random_state=42)

In [24]:
X=df_encoded.drop('loan_status',axis=1)
y=df_encoded['loan_status']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [26]:
Percep.fit(X_train,y_train)

Perceptron(random_state=42)

In [27]:
y_pred=Percep.predict(X_test)

In [28]:
accuracy_score(y_test,y_pred)

0.857984220468941

In [29]:
ANN=Sequential([
    Dense(32, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

In [30]:
ANN.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [31]:
hist_ann=ANN.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=8,verbose=1,epochs=15)

Epoch 1/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 3s 437us/step - accuracy: 0.8926 - loss: 0.2368 - val_accuracy: 0.9113 - val_loss: 0.1992
Epoch 2/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 406us/step - accuracy: 0.9104 - loss: 0.1993 - val_accuracy: 0.9177 - val_loss: 0.1903
Epoch 3/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 406us/step - accuracy: 0.9133 - loss: 0.1925 - val_accuracy: 0.9150 - val_loss: 0.1859
Epoch 4/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 405us/step - accuracy: 0.9153 - loss: 0.1880 - val_accuracy: 0.9177 - val_loss: 0.1810
Epoch 5/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 411us/step - accuracy: 0.9174 - loss: 0.1849 - val_accuracy: 0.9160 - val_loss: 0.1828
Epoch 6/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 414us/step - accuracy: 0.9183 - loss: 0.1819 - val_accuracy: 0.9150 - val_loss: 0.1846
Epoch 7/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 437us/step - accuracy: 0.9186 - loss: 0.1806 - val_accuracy: 0.9195 - val_loss: 0.1760
Epoch 8/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 414us/step - accuracy: 0.9199 - loss: 0.1787 - val_accuracy: 0.9159 - val_loss: 0.1806
Epoch 9/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 412us/step - accuracy: 0.9197 - loss: 0.1771 - val_accuracy: 0.9179 - val_loss: 0.1795
Epoch 10/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 411us/step - accuracy: 0.9205 - loss: 0.1760 - val_accuracy: 0.9192 - val_loss: 0.1777
Epoch 11/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 413us/step - accuracy: 0.9204 - loss: 0.1754 - val_accuracy: 0.9197 - val_loss: 0.1750
Epoch 12/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 408us/step - accuracy: 0.9221 - loss: 0.1742 - val_accuracy: 0.9208 - val_loss: 0.1753
Epoch 13/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 425us/step - accuracy: 0.9224 - loss: 0.1730 - val_accuracy: 0.9168 - val_loss: 0.1834
Epoch 14/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 408us/step - accuracy: 0.9220 - loss: 0.1728 - val_accuracy: 0.9208 - val_loss: 0.1746
Epoch 15/15
4500/4500 ━━━━━━━━━━━━━━━━━━━━ 2s 408us/step - accuracy: 0.9226 - loss: 0.1717 - val_accuracy: 0.9213 - val_loss: 0.1762

In [32]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 35994 entries, 23839 to 15799
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      35994 non-null  float64
 1   person_gender                   35994 non-null  int64
 2   person_income                   35994 non-null  float64
 3   person_emp_exp                  35994 non-null  float64
 4   loan_amnt                       35994 non-null  float64
 5   loan_int_rate                   35994 non-null  float64
 6   loan_percent_income             35994 non-null  float64
 7   cb_person_cred_hist_length      35994 non-null  float64
 8   credit_score                    35994 non-null  float64
 9   previous_loan_defaults_on_file  35994 non-null  int64
 10  person_education_Associate      35994 non-null  int64
 11  person_education_Bachelor       35994 non-null  int64
 12  person_education_Doctorate      35994 non-null  int64
 13  person_education_High School    35994 non-null  int64
 14  person_education_Master         35994 non-null  int64
 15  person_home_ownership_MORTGAGE  35994 non-null  int64
 16  person_home_ownership_OTHER     35994 non-null  int64
 17  person_home_ownership_OWN       35994 non-null  int64
 18  person_home_ownership_RENT      35994 non-null  int64
 19  loan_intent_DEBTCONSOLIDATION   35994 non-null  int64
 20  loan_intent_EDUCATION           35994 non-null  int64
 21  loan_intent_HOMEIMPROVEMENT     35994 non-null  int64
 22  loan_intent_MEDICAL             35994 non-null  int64
 23  loan_intent_PERSONAL            35994 non-null  int64
 24  loan_intent_VENTURE             35994 non-null  int64
dtypes: float64(8), int64(17)
memory usage: 7.1 MB

In [34]:
ANN.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,133 (16.15 KB)

 Trainable params: 1,377 (5.38 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,756 (10.77 KB)