In [1]:
import numpy as np
import pandas as pd


Creating a DataFrame

In [2]:
data={
    "Name":['Chris', "Tom",'Robert','Jack'],
    "Age":[51,48,54,65],
    'City': ['NY','LA','NY','LV'],
    'Salary':[5000000,4005500,4800000,5200000]
}

In [39]:
df=pd.DataFrame(data,index=['A','B','C','D'])

In [40]:
df

     Name  Age City   Salary
A   Chris   51   NY  5000000
B     Tom   48   LA  4005500
C  Robert   54   NY  4800000
D    Jack   65   LV  5200000


Selection and Indexing of columns

In [19]:
df['City']

0    NY
1    LA
2    NY
3    LV
Name: City, dtype: str

In [21]:
df[['Name','City']][0:3]

     Name City
0   Chris   NY
1     Tom   LA
2  Robert   NY


Creating New Column

In [22]:
df['Sex']=['M','F','M','F']

In [23]:
df

     Name  Age City   Salary Sex
0   Chris   51   NY  5000000   M
1     Tom   48   LA  4005500   F
2  Robert   54   NY  4800000   M
3    Jack   65   LV  5200000   F


Removing Column

In [25]:
df.drop('Name',axis=1)

   Age City   Salary Sex
0   51   NY  5000000   M
1   48   LA  4005500   F
2   54   NY  4800000   M
3   65   LV  5200000   F

In [26]:
df

     Name  Age City   Salary Sex
0   Chris   51   NY  5000000   M
1     Tom   48   LA  4005500   F
2  Robert   54   NY  4800000   M
3    Jack   65   LV  5200000   F

In [27]:
df.drop(['Name','Age'],axis=1)

  City   Salary Sex
0   NY  5000000   M
1   LA  4005500   F
2   NY  4800000   M
3   LV  5200000   F

In [28]:
df.drop('Sex',axis=1,inplace=True)

In [29]:
df

     Name  Age City   Salary
0   Chris   51   NY  5000000
1     Tom   48   LA  4005500
2  Robert   54   NY  4800000
3    Jack   65   LV  5200000


Selecting a row

In [30]:
df[0:]

     Name  Age City   Salary
0   Chris   51   NY  5000000
1     Tom   48   LA  4005500
2  Robert   54   NY  4800000
3    Jack   65   LV  5200000

In [31]:
df[0:1]

    Name  Age City   Salary
0  Chris   51   NY  5000000

In [32]:
df.loc(0)

In [42]:
df.loc['A']

Name        Chris
Age            51
City           NY
Salary    5000000
Name: A, dtype: object

In [43]:
df.loc[['A','B']]

    Name  Age City   Salary
A  Chris   51   NY  5000000
B    Tom   48   LA  4005500

In [37]:
df.iloc[2]

Name       Robert
Age            54
City           NY
Salary    4800000
Name: 2, dtype: object

In [50]:
df.iloc[[1,2]]

     Name  Age City   Salary
B     Tom   48   LA  4005500
C  Robert   54   NY  4800000


Selecting Subset of rows and columns

In [51]:
df.iloc[[0,1]][['City','Salary']]

  City   Salary
A   NY  5000000
B   LA  4005500

In [52]:
df.iloc[[2,3]][['Name','Age']]

     Name  Age
C  Robert   54
D    Jack   65


Conditional Selection

In [61]:
df[(df['Age']>40) & (df['City']=='LA')]

  Name  Age City   Salary
B  Tom   48   LA  4005500

In [63]:
 df[df['Age']>50]

     Name  Age City   Salary
A   Chris   51   NY  5000000
C  Robert   54   NY  4800000
D    Jack   65   LV  5200000