In [2]:
import numpy as np 
import pandas as pd

In [35]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)


Finding Missing Data

In [36]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [37]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [38]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool


Removing Missing Data

In [39]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [40]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0


Filling missing value

In [41]:
df.fillna(2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  2.0
2  2.0  3  3.0  2.0
3  4.0  4  2.0  2.0
4  5.0  5  2.0  5.0

In [42]:
values={'A':2,'B':6,'C':8}

In [43]:
df.fillna(value=values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  2.0  3  3.0  NaN
3  4.0  4  8.0  NaN
4  5.0  5  8.0  5.0

In [33]:
a=dict(df.mean())

In [26]:
a

{'A': np.float64(3.0),
 'B': np.float64(3.0),
 'C': np.float64(2.0),
 'D': np.float64(3.0)}

In [28]:
df.fillna(value=a)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [29]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0